[build]
  command = "yarn build"
  publish = "dist/client"
  functions = "dist/server"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/"
    [headers.values]
      Access-Control-Allow-Origin = "*"